name: .NET 8 Continuous Integration with GitHub and Nuget Packages

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Generate Release
      run: dotnet build -c release

    - name: Generate Nuget Package
      run: dotnet pack -c release -o ./dist/

    #- name: Push Nuget Package
      #run: dotnet nuget push "./dist/*" -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
